title: Thomas M. FONTAINE # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.lyceedadultes.fr/">Lyc√©e d'Adultes de la Ville de Paris</a> Philippe Leclerc de Hauteclocque.
  <br><br>
  Contact : <a href="mailto:thomas.fontaine.lavp@laposte.net">thomas.fontaine.lavp@laposte.net</a>
  <br><br>
  <a href="https://github.com/thomas-m-fontaine/thomas-m-fontaine.github.io/blob/master/images/Carte_professionnelle.pdf">SOI</a> ; <a href="https://www.linkedin.com/in/thomas-m-fontaine">LinkedIn</a> ; <a href="https://orcid.org/0000-0003-1948-0609">ORCID</a>
  <br>
theme: jekyll-theme-minimal
